### ISSUE TITLE
Sam file output error

### ISSUE THREAD

**Issue by rafaeltiveron** [hsinnan75/Dart#2]
Hello

When assembling from single-end files, sometimes appears this in my sam output file:

16543 `M01506:25:000000000-AF8M6:1:1101:7861:1913	0	KQ035508.1	30405	0	93M	*	0	0	CCTGCGTTATTTTTTGACAGATGTACCGCCCCAGTCAAACTCCCCGCCTGGCAGTGTCCTCGAATCGGATCACGCTAGGGAGTATGTTGCCGA	CCCCCGGGGGGGGGGGGGGGFGFGFFF7C+CFEGGCGEEDFEGGGEGGGG,==8D,?;8=9D**,:8<*55=756))3))0)));CC**5*::	NM:i:0	AS:i:93	XS:i:93`
16544 `M01506:25:000000000-AF8M6:1:1101:13475:1921	16	KQ034152.1	1633006	50	17S80M	*	0	0	ACCGGAGCAGCGGCAAGAGTTGAATCACATGCCTACTCAAGTGAATCAGCAGCAAGAGATGCATCACCTTCCACCAGCGCAACAGCAGACAAACAAT		NM:i:18	AS:i:79	XS:i:0`
16545 `M01506:25:000000000-AF8M6:1:1101:20650:1922	16	KQ034201.1	830751	50	52M84N47M	*	0	0	CTCATCAACAAACCCAGCAGCAAAGTCACCAGCAAACCCATCATCAAACTCATCAACAAACTCACCAGCAAGCCCACCAACAAGTCCGTCAAGAACACC		NM:i:0	AS:i:99	XS:i:0`

When trying to convert to bam file, I receive this:

`[E::sam_parse1] SEQ and QUAL are of different length
[W::sam_read1] Parse error at line 16544
[main_samview] truncated file.
`

It seems some lines are not getting sequence QUAL codes. Assembling from paired-ends, this doesn't happen and all is ok.

**Comment by hsinnan75** [comment]
Hi,

Thank you for reporting this bug to us. We've updated a new version. If the
problem persists, please let us know. Thank you very much.

Best regards,

Hsin-Nan

**Comment by OlgaVT** [comment]
Hi,

this problem persists, but I have installed Dart from conda. Should I update it or the conda version is the latest?

Thank you!

**Comment by OlgaVT** [comment]
Hi,

I also have a problem with the output sam file from the paired-end alignment. I tried to filter it with samtools view, and this is an error message:

[E::sam_parse1] CIGAR and query sequence are of different length
[W::sam_read1] Parse error at line 1545
[main_samview] truncated file.

The output file is truncated - there is no sequence part in the line:

`read1829        147     X       100593666       50      2S150M  =       100585298       -8520           *       NM:i:2  AS:i:150        XS:i:0`


I have installed Dart from conda.
Thank you!

**Comment by hsinnan75** [comment]
Hi, could you give me your fastq file or paste the read sequence at line 1545 of the same file and the reference file (accession) ? Thank you!!

**Comment by OlgaVT** [comment]
Hi,
the read at line 1545: `ATGGGGATCCCTTCAGAGCTGGTATTTTGAATTCAAGCCAAGCTGCTGAGCTAATTACTAAGAATTCCAACAGTTTTCTTGGCAGCCTTGACTAAACAGCAAATGATAGTTTGCAAACCAGCCTATAAAGTATTTTCCCCTTGTGTTAAG` 

The reference file:  GRCh38.p13

It was a paired-end. The other read is:
`TGGCCCTAACTCTAATTGTCCTGTTTTGGGGGAGCAAGCACTTCTGGCCGGAGGTACCCAAAAAAGGTAGCTTAAAGAAGCAGCATAGGTTTTAGGTGATCCCTCAGCTTAACACAAGGGGAAAATACTTTATAGGCTGGTTTGCAAACT`

The both lines in sam file:
`read1829	99	X	100585298	50	66M8261N84M2S	=	100593666	8520	TGGCCCTAACTCTAATTGTCCTGTTTTGGGGGAGCAAGCACTTCTGGCCGGAGGTACCCAAAAAAGGTAGCTTAAAGAAGCAGCATAGGTTTTAGGTGATCCCTCAGCTTAACACAAGGGGAAAATACTTTATAGGCTGGTTTGCAAACT--	*	NM:i:2	AS:i:150	XS:i:0`
`read1829	147	X	100593666	50	2S150M	=	100585298	-8520		*	NM:i:2	AS:i:150	XS:i:0`

Thank you!

**Comment by hsinnan75** [comment]
Thank you for the data. It's very strange that the sequence contains "--" at the end. Is it possible that the input data looks that way? I run the two sequences and the result looks good. The CIGAR and the sequence are of the same length. Could you please check your original data ? Thank you!

**Comment by OlgaVT** [comment]
Original data looks like this for R1:
`>read1829
TGGCCCTAACTCTAATTGTCCTGTTTTGGGGGAGCAAGCACTTCTGGCCGGAGGTACCCAAAAAAGGTAGCTTAAAGAAGCAGCATAGGTTTTAGGTGATCCCTCAGCTTAACACAAGGGGAAAATACTTTATAGGCTGGTTTGCAAACT`

And for R2:
`>read1829
ATGGGGATCCCTTCAGAGCTGGTATTTTGAATTCAAGCCAAGCTGCTGAGCTAATTACTAAGAATTCCAACAGTTTTCTTGGCAGCCTTGACTAAACAGCAAATGATAGTTTGCAAACCAGCCTATAAAGTATTTTCCCCTTGTGTTAAG`

I will try to align using not fasta, but fastq files and write about the results.

Thank you!

**Comment by OlgaVT** [comment]
Hi again,

I tried with the fastq files - the sam problem has disappeared. Still do not know what exactly causes it for the first time - maybe some problems in fasta files format. Thank you very much for your time and help!

**Comment by hsinnan75** [comment]
Hi, I've fixed the bug. It happens when the sequence data contains unexpected characters. You may download the latest version (1.3.9) and try again. Thank you! The bioconda will be updated in a few hours.

**Comment by OlgaVT** [comment]
Thank you very much!
